const mockQuizQuestions = [
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'easy',
		question: 'Which of these is NOT a player class in Team Fortress 2?',
		correct_answer: 'Healer',
		incorrect_answers: ['Demoman', 'Pyro', 'Spy'],
		answers: ['Spy', 'Demoman', 'Pyro', 'Healer'],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'Which of these levels does NOT appear in the console/PC versions of the game &quot;Sonic Generations&quot;?',
		correct_answer: 'Mushroom Hill',
		incorrect_answers: ['City Escape', 'Planet Wisp', 'Sky Sanctuary'],
		answers: ['City Escape', 'Mushroom Hill', 'Planet Wisp', 'Sky Sanctuary'],
	},
	{
		category: 'Science & Nature',
		type: 'multiple',
		difficulty: 'easy',
		question: 'How many planets make up our Solar System?',
		correct_answer: '8',
		incorrect_answers: ['7', '9', '6'],
		answers: ['7', '6', '9', '8'],
	},
	{
		category: 'Geography',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'Which of the following European languages is classified as a &quot;language isolate?&quot;',
		correct_answer: 'Basque',
		incorrect_answers: ['Galician', 'Maltese', 'Hungarian'],
		answers: ['Hungarian', 'Basque', 'Galician', 'Maltese'],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'Which of these is NOT a playable character in the 2016 video game Overwatch?',
		correct_answer: 'Invoker',
		incorrect_answers: ['Mercy', 'Winston', 'Zenyatta'],
		answers: ['Winston', 'Zenyatta', 'Invoker', 'Mercy'],
	},
	{
		category: 'Vehicles',
		type: 'multiple',
		difficulty: 'easy',
		question: 'What UK Train does NOT go over 125MPH?',
		correct_answer: 'Sprinter',
		incorrect_answers: ['Class 43', 'Javelin', 'Pendolino'],
		answers: ['Sprinter', 'Javelin', 'Class 43', 'Pendolino'],
	},
	{
		category: 'General Knowledge',
		type: 'multiple',
		difficulty: 'easy',
		question: 'Who is depicted on the US hundred dollar bill?',
		correct_answer: 'Benjamin Franklin',
		incorrect_answers: [
			'George Washington',
			'Abraham Lincoln',
			'Thomas Jefferson',
		],
		answers: [
			'George Washington',
			'Benjamin Franklin',
			'Abraham Lincoln',
			'Thomas Jefferson',
		],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'In the game Battleblock Theater, what was the name of the voice actor who voiced the narrator?',
		correct_answer: 'Will Stamper',
		incorrect_answers: ['Steve Blum', 'Richard Epcar', 'Yuri Lowenthal'],
		answers: ['Yuri Lowenthal', 'Steve Blum', 'Richard Epcar', 'Will Stamper'],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'In Super Mario Bros., who informs Mario that the princess is in another castle?',
		correct_answer: 'Toad',
		incorrect_answers: ['Luigi', 'Yoshi', 'Bowser'],
		answers: ['Bowser', 'Toad', 'Yoshi', 'Luigi'],
	},
	{
		category: 'History',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'Which of the following countries was not an axis power during World War II?',
		correct_answer: ' Soviet Union',
		incorrect_answers: ['Italy', 'Germany', 'Japan'],
		answers: ['Japan', ' Soviet Union', 'Germany', 'Italy'],
	},
	{
		category: 'Vehicles',
		type: 'multiple',
		difficulty: 'easy',
		question: 'The LS2 engine is how many cubic inches?',
		correct_answer: '364',
		incorrect_answers: ['346', '376', '402'],
		answers: ['402', '364', '376', '346'],
	},
	{
		category: 'History',
		type: 'multiple',
		difficulty: 'easy',
		question: 'In 1453, which important city fell?',
		correct_answer: 'Constantinople',
		incorrect_answers: ['Rome', 'Hamburg', 'Athens'],
		answers: ['Constantinople', 'Hamburg', 'Athens', 'Rome'],
	},
	{
		category: 'Entertainment: Video Games',
		type: 'multiple',
		difficulty: 'easy',
		question:
			'Which Pok&eacute;mon can learn the move &quot;Secret Power&quot; by leveling up?',
		correct_answer: 'Audino',
		incorrect_answers: ['Type:Null', 'Arceus', 'Silvally'],
		answers: ['Arceus', 'Type:Null', 'Audino', 'Silvally'],
	},
	{
		category: 'History',
		type: 'multiple',
		difficulty: 'easy',
		question: 'On what street did the 1666 Great Fire of London start?',
		correct_answer: 'Pudding Lane',
		incorrect_answers: [
			'Baker Street',
			'Houses of Parliament',
			'St Paul&#039;s Cathedral',
		],
		answers: [
			'Baker Street',
			'Pudding Lane',
			'St Paul&#039;s Cathedral',
			'Houses of Parliament',
		],
	},
	{
		category: 'Entertainment: Music',
		type: 'multiple',
		difficulty: 'easy',
		question: 'What is the name of Rivers Cuomo&#039;s wife?',
		correct_answer: 'Kyoko Ito',
		incorrect_answers: ['Yoko Ono', 'Kyary Pamyu Pamyu', 'LiSA'],
		answers: ['Kyary Pamyu Pamyu', 'LiSA', 'Kyoko Ito', 'Yoko Ono'],
	},
];

export default mockQuizQuestions;
